### DISCUSSION TITLE
K8s Pod CreateContainerError  rootfs mounts caused: rootfs_linux.go:1180: mounting sysfs to rootfs

### DISCUSSION THREAD

**Discussion by xlw712** [nestybox/sysbox#750] [Q&A] [answered]
I refer to the documentation now  https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md#kubernetes-distro-requirements  install sysbox.
Installed via k8s, but found the following error when starting the pod
Environmental information
K8s=1.27.0
SysBox.image=sysbox-deploy-k8s:v0.6.2
K8s.Node.OS below
```
LSB Version:	core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```
Pod Error Msg
 Warning  Failed     86s (x3 over 111s)    kubelet            (combined from similar events): Error: container create failed: time="2023-11-24T14:08:37+08:00" level=error msg="container_linux.go:424: starting container process caused: process_linux.go:607: container init caused: rootfs_linux.go:70: setting up rootfs mounts caused: rootfs_linux.go:1180: mounting \"sysfs\" to rootfs \"/var/lib/sysbox/shiftfs/8286d1f5-12ac-4bec-b898-66181d388adb\" at \"/sys\" caused: mount through procfd: operation not permitted"
![image](https://github.com/nestybox/sysbox/assets/10722207/eaa6fcb4-48c2-4776-99a1-a7c2f9286b9f)

sysbox-deploy pod enable 
![image](https://github.com/nestybox/sysbox/assets/10722207/68edf2eb-4e72-48d3-8843-01283cce0918)

Is there any way?   Very urgent  Thanks

**Comment by ctalledo** [comment]
Hi @xlw712, thanks for giving Sysbox a try.

That error typically occurs when you miss the user-ns annotation in the pod spec:

```
apiVersion: v1
kind: Pod
metadata:
  name: ubu-bio-systemd-docker
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"         <<< HERE
spec:
  runtimeClassName: sysbox-runc
  containers:
  - name: ubu-bio-systemd-docker
    image: registry.nestybox.com/nestybox/ubuntu-bionic-systemd-docker
    command: ["/sbin/init"]
  restartPolicy: Never
```

Can you double check that annotation is present in your pod spec?

Thanks!

**Reply by xlw712** [reply, marked as answer]
Thanks you reply,I used the pod spec for annotations. here's my pod template.He's still reporting an error
```
apiVersion: v1
kind: Pod
metadata:
  name: pixiu-cicd-{{ POD_POSTFIX }}
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
  labels:
    app: web
spec:
  nodeSelector:
    using: pixiu_cicd
  runtimeClassName: sysbox-runc
  containers:
    - name: gocd-agent-container
      image: gocd-agent-docker-dind:aliunx3.8
      resources:
        requests:
          memory: 125000000Ki
          cpu: 28
        limits:
          memory: 125000000Ki
          cpu: 30
```
But before you could respond, I found a solution , It comes from #67 
![image](https://github.com/nestybox/sysbox/assets/10722207/0922d623-1340-4539-9e79-2d0dacf2a8a9)
mount by changing solution, I'm Posting this in the hope that it will help others
Before change
```
findmnt | grep "sysfs"
├─/sys                                                                                                                       sysfs                                          sysfs       rw,nosuid,nodev,noexec,relatime
```
Fix Step
```
mount -o remount,rw /sys /sys
```
```
findmnt | grep "sysfs"
├─/sys                                                                                                                       sysfs                                          sysfs       rw,relatime
```
