### ISSUE TITLE
VNC (X Server, Guacd, Guacamole) does not work after installing sysbox on docker host

### ISSUE THREAD

**Issue by rubenanapu** [nestybox/sysbox#383]
I'm used to launching 4 containers (**VNC + Guacd + Guacamole + AnotherContainer**)  and I can launch a graphical app in **AnotherContainer**, and I can always visualize it, either directly connecting to VNC or through Guacamole.

However, since I installed **sysbox** in the Docker Host, the graphical tools doesn't work as expect anymore.

If I put `runtime: sysbox-runc` in the docker-compose file, when I try to run a graphical app it says it cannot connect to the **DISPLAY**.

But If I remove `runtime: sysbox-runc` from the docker-compose file, I can launch graphical things but parts of the window are missing.

I tested installing sysbox on a docker host that runs **Ubuntu 18.04**, and also on another host that runs **Ubuntu 20.04** but the problem happens in both cases.

Has anybody else experienced this? If so, how did you solve it?

**Comment by rodnymolina** [comment]
@rubenanapu, thanks for reporting this.

I can think of a couple of issues that may explain what you are observing when you make use of "sysbox-runc" in your docker-compose file. But none of that would explain your second issue: parts of the window are missing when you don't use sysbox-runc.

Let's step back for a sec and try to understand your scenario in more details. Can you please share your docker-compose to help me reproduce the issue locally?

Thanks.

**Comment by rubenanapu** [comment]
Hi @rodnymolina ,

sure. This is the `docker-compose.yml` file you can use to reproduce the issue:

```yaml
version: '3'

services:
  vnc:
    image: x11vnc/desktop:latest
    container_name: vnc
    hostname: vnc
    ports:
      - 5901:5901
      - 6901:6901
      - 6080:6080
    volumes:
      - x11_volume:/tmp/.X11-unix:rw
    command:
      - sudo chown -R ubuntu:ubuntu /tmp/.X11-unix && /sbin/my_init --quiet -- /sbin/setuser ubuntu && startvnc.sh >> /home/ubuntu/.log/vnc.log

  ros:
    image: osrf/ros:noetic-desktop-full
    container_name: ros
    hostname: ros
    environment:
      - "QT_X11_NO_MITSHM=1"  #fix some QT bugs
      - DISPLAY=:0
    volumes:
      - x11_volume:/tmp/.X11-unix:rw
    depends_on:
      - vnc
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - source /opt/ros/noetic/setup.bash && stdbuf -o L roslaunch gazebo_ros empty_world.launch --screen

volumes:
  x11_volume:
```

I normally do the following:

1. Stop any existing container of this docker-compose with:  `docker-compose down`
2. Remove any volume named `x11_volume` with: 
> `docker volume rm -f $(docker volume ls --filter 'name=x11_volume' -q)`
3. Start the containers with: `docker-compose up`

After starting the containers, you should see the `vnc` container printing something like this:
> vnc    | Open your web browser with URL:
> vnc    |     http://localhost:6080/vnc.html?resize=downscale&autoconnect=1&password=ueuO4Apd

You can then open that URL in your browser in order to see the Graphical Tools. The URL/password will be different each time you run `docker-compose up`. You should also repeat the 3 steps each time you want to run *docker-compose up* just to make sure you will be able to access the Graphical Tools using the web browser.

When you open the web browser, you will see something like this:
![x11-broken-with-sysbox](https://user-images.githubusercontent.com/30424797/142304457-b0ecaf88-0da2-4572-a734-f81bcbdfb6fb.png)



Before starting sysbox, the way it originally works is like this:

![before-sysbox-ce](https://user-images.githubusercontent.com/30424797/142304346-db1ce4b0-0bed-43c5-801d-5b2d2ca923aa.png)

Please let me know if I can help you diagnose it in any other way.
