### ISSUE TITLE
Gitlab runner Kubernetes executor

### ISSUE THREAD

**Issue by gdespreslaberge** [nestybox/sysbox#516]
Hi,

We're trying to get sysbox running on our gitlab runners. We've pushed gitlab to include `runtimeClassName` in the runners and now that it's integrated, we're trying to make it run but running into some issues.

The runners toml config:
```
    [[runners]]
      name = "Linux Sysbox (https://square/runners)"
      [runners.feature_flags]
        FF_KUBERNETES_HONOR_ENTRYPOINT = true
      [runners.kubernetes]
        helper_image = "gitlab/gitlab-runner:alpine3.14-bleeding"
```

The CI Job:
```yaml
default:
  image: 
    name: registry.nestybox.com/nestybox/ubuntu-bionic-systemd-docker
  retry: 2
  tags:
  - square-linux-k8s-sysbox

stages:
  - test

test-job:
  stage: test  
  script:
    - ps aux
    - systemctl status docker
    - docker ps
    - docker build .
```

So the initial issue was that we are not getting any shell since the systemd is a blocking process.
We've tried using a custom script via a service file as suggested [here](https://github.com/nestybox/sysbox/issues/94) but that did not work either as for some reason docker and the service won't start at init (but can be started manually.

I've exhausted all my potential solutions. We would really like to use sysbnox in our prod environment, could you give us a hand?

Thanks

PS:
I can get things running in a simple pod with `kubectl apply -f ` and everything works as intended.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: docker-test
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
spec:
  runtimeClassName: sysbox-runc
  containers:
  - name: doocker-test
    image: registry.nestybox.com/nestybox/ubuntu-bionic-systemd-docker
```
