### ISSUE TITLE
Issues running DIND in Openstack K8S cluster

### ISSUE THREAD

**Issue by robert-gomes** [nestybox/sysbox#602]
We have a K8S cluster running on Openstack, the nodes are Ubuntu 20.04 (kernel 5.4). The installation goes smoothly using K8S daemonset from this document https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md
Pretty much vanilla installation, default configurations.
We can run containers fine as well, however we aren't able to run DIND within these containers.
example pod definition
```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: m1-large-sysbox
  name: ubu-bio-systemd-docker
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
spec:
  nodeSelector:
    sysbox-runtime: "running"
  runtimeClassName: sysbox-runc
  containers:
  - name: ubu-bio-systemd-docker
    image: registry.nestybox.com/nestybox/ubuntu-bionic-systemd-docker
    command: ["/sbin/init"]
  restartPolicy: Never
```
trying to run docker within the container
```bash
root@ubu-bio-systemd-docker:/# docker run hello-world
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "sysfs" to rootfs at "/sys": mount sysfs:/sys (via /proc/self/fd/6), flags: 0xf: no such file or directory: unknown.
ERRO[0000] error waiting for container: context canceled
```
We tested the same deployment setup on GCP and AWS (Ubuntu 20.04 kernel < 5.12 ) and all works well, let me know if any additional diagnostic info would be helpful.
