### ISSUE TITLE
EKS 1.28 won't install sysbox through sysbox-deploy-k8s daemonset

### ISSUE THREAD

**Issue by sofusalbertsen** [nestybox/sysbox#783]
Trying to upgrade to EKS 1.28, in EU-north-1, with your [sysbox-deploy-k8s daemonset](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md), i get the following error:

```
k logs -n kube-system sysbox-deploy-k8s-z9mh9 
ERROR: Sysbox is not supported on this Kubernetes version (v1.28).
```

I create the cluster using eksctl, with the following cluster config:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "cluster"
  region: "eu-north-1"
  version: "1.28"
  tags:
    owner: "me"
    karpenter.sh/discovery: "-cluster"

iam:
  withOIDC: true
  vpcResourceControllerPolicy: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
        labels: {aws-usage: "cluster-ops"}
      attachPolicyARNs:
        - arn:aws:iam::123456:policy/AWSLoadBalancerControllerIAMPolicy
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true
    - metadata:
        name: external-dns
        namespace: external-dns
      attachPolicyARNs:
        - arn:aws:iam::123456:policy/ExternalDNSIAMPolicy


karpenter:
  version: v0.29.0

addons:
  - name: coredns
    version: "latest"
  - name: vpc-cni
    version: "latest"
  - name: kube-proxy
    version: "latest"
  - name: aws-ebs-csi-driver
    version: "latest"

nodeGroups:
  - name: "cluster-default-workers"
    amiFamily: Ubuntu2004
    instanceType: "t3.xlarge"
    desiredCapacity: 1
    availabilityZones: ["eu-north-1a"]
    labels:
      owner: "sofus.albertsen"
      role: "workers"
      sysbox-install: "yes"
```

Steps to reproduce:
* create cluster with eksctl
* kubectl apply -f "https://raw.githubusercontent.com/nestybox/sysbox/v0.6.3/sysbox-k8s-manifests/sysbox-install.yaml"
* See that sysbox is not getting installed.
