### ISSUE TITLE
Can not install QEMU for set multi arch on Pod

### ISSUE THREAD

**Issue by Rory-Z** [nestybox/sysbox#823]
Hello guys,
I installed sysbox on AWS EKS 1.29 like https://github.com/nestybox/sysbox/issues/820, and I created pod like this

```
apiVersion: v1
kind: Pod
metadata:
  name: dind
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
spec:
  runtimeClassName: sysbox-runc
  containers:
  - name: dind
    image: docker:dind
```

Now I can running docker command in pod without privileged for pod, all looks good 

But when I install https://github.com/tonistiigi/binfmt for docker buildx, I got error:
```
$ docker run --rm --privileged docker.io/tonistiigi/binfmt:latest --install all
error: operation not permitted
cannot mount binfmt_misc filesystem at /proc/sys/fs/binfmt_misc
main.run
	/src/cmd/binfmt/main.go:183
main.main
	/src/cmd/binfmt/main.go:170
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1571
```
Any ideas ?
