### ISSUE TITLE
Failure to start daemon for DinD in a sysbox-runc K8s pod

### ISSUE THREAD

**Issue by pschwartz** [nestybox/sysbox#917]
Currently I am facing an issue while attempting to run a DinD style container in sysbox.

I have tried the following containers to run as the service container:
1. docker:28.0.0-dind
2. docker:27.5.1-dind
3. yobasystems-alpine-docker:dind
4. nestybox/alpine-docker:latest

All of these have failed 95% of the times started with the following error:
```
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to register "bridge" driver: Cannot read IP forwarding setup: read /proc/sys/net/ipv4/ip_forward: input/output error
```

As stated the other 5% the container will start up correctly.

K8s Manifest:
```
apiVersion: v1
kind: Pod
metadata:
  name: ci-test
spec:
  containers:
  - name: cli
    image: docker:28.0.0-cli
    resources:
      requests:
        cpu: 1000m
        memory: 1G
    command: ["sleep 5000"] 
  - name: dind
    image: docker:28.0.0-dind
    args: ["dockerd"]
    env:
    - name: SYSBOX_ALLOW_TRUSTED_XATTR
      value: "FALSE"
    resources:
      requests:
        cpu: 4000m
        memory: 4G
  nodeSelector: sysbox
  runtimeClassName: sysbox-runc
```

Watching the logs is when I see the error in the dind container in the pod, the times when it has come up, I have been able to verify by exec'ing into the cli pod and running a `DOCKER_HOST=tcp://localhost:2375 docker info`

This is running in EKS on Ubuntu 22.04 nodes using `registry.nestybox.com/nestybox/sysbox-deploy-k8s:v06.4`
