### ISSUE TITLE
Failed to create pod sandbox: rpc error: code = Unknown desc = RuntimeHandler "sysbox-runc" not supported

### ISSUE THREAD

**Issue by santurini** [nestybox/sysbox#936]
I have a fresh installed RKE cluster and a successful sysbox daemonset.
When I try to schedule a pod I get the aforementioned error even if I have the runtime class defined.

More details are provided in #673

**Comment by ctalledo** [comment]
Hi @santurini, in the pod spec, in addition to specifying the runtime class, did you also add the userns annotation?

```
apiVersion: v1
kind: Pod
metadata:
  name: ubu-bio-systemd-docker
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"          <<< HERE
spec:
  runtimeClassName: sysbox-runc                                           <<< HERE
  containers:
  - name: ubu-bio-systemd-docker
    image: registry.nestybox.com/nestybox/ubuntu-bionic-systemd-docker
    command: ["/sbin/init"]
  restartPolicy: Never
```

Let us know. Thanks.
